spring.application.name=test
server.port=9080
spring.profiles.active=prod



#spring.datasource.url=jdbc:postgresql://localhost:5432/duk_test
spring.datasource.url=jdbc:postgresql://testdb.cluster-ch6iwaqqmi9m.ap-south-1.rds.amazonaws.com:5432/test
spring.datasource.username=postgres
#spring.datasource.password=Sgou2025%arNprod
spring.datasource.password=Test-Passwd2026#
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration/common
spring.flyway.baseline-on-migrate=true

spring.datasource.hikari.pool-name=TestHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
