spring.application.name=test
server.port=9080
spring.profiles.active=prod
spring.config.import=classpath:flyway.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/duk_test
#spring.datasource.url=jdbc:postgresql://sgouprod.cluster-ccsglsrs3rmm.ap-south-1.rds.amazonaws.com:5432/test


#spring.datasource.url=jdbc:postgresql://testdb.cluster-ch6iwaqqmi9m.ap-south-1.rds.amazonaws.com:5432/test
spring.datasource.username=postgres
#spring.datasource.password=Sgou2025%arNprod
spring.datasource.password=123456

#spring.datasource.password=Test-Passwd2026#
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.hikari.pool-name=TestHikariPool
#spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=35000
pring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.connection-test-query=SELECT 1

#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari.pool.HikariPool=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.connect-timeout=2000
spring.data.redis.timeout=2000
